#!/bin/sh -e

CONFIG_DIR="/etc/kmip2pkcs11"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -d ${CONFIG_DIR} ]; then
        rm -R ${CONFIG_DIR}
    fi
    ;;
esac

#DEBHELPER#
