[project]
name = "kmip2pkcs11-manual"
version = "0.1.0"
description = "Building the kmip2pkcs11 manual"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sphinx-version-warning==1.1.2",
    "sphinx-copybutton>=0.5.2",
    "sphinx-notfound-page>=1.0.4",
    "sphinx-rtd-theme>=3.0.1",
    "sphinx-substitution-extensions>=2024.10.17",
    "sphinx-tabs>=3.4.7",
    "sphinx>=8.1.3",
    "toml>=0.10.2",
]
